name: Feature Request
description: Submit a feature request
labels: ["enhancement"]
assignees:
  - arcanistzed
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this feature request!"
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Is your feature request related to a problem?
      placeholder: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Describe the solution you'd like
      placeholder: "A clear and concise description of what you want to happen."
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives"
      description: "Describe alternatives you've considered"
      placeholder: "A clear and concise description of any alternative solutions or features you've considered."
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Additional context
      placeholder: "Add any other information such as screenshots which are relevant to the feature request here."
